### ISSUE TITLE
Device should be a parameter passed to summary

### ISSUE THREAD

**Issue by futscdav** [TylerYep/torch-summary#2]
Just because cuda is available doesn't mean I want to run the summary using it. 

My use case: model too large to fit onto GPU on the machine that I run summary on.

Better yet, you can move the input to whatever device the model is currently on.

**Comment by TylerYep** [comment]
Good point, I'll add this as a parameter.

**Comment by TylerYep** [comment]
I released the new version, it should be pip installable/upgradable now.
