### ISSUE TITLE
ModuleList not showing up in summary

### ISSUE THREAD

**Issue by roym899** [TylerYep/torch-summary#9]
Hi,
it looks like modules wrapped in a `ModuleList` don't show up in the summary (looks like the params are counted in the total though). 

Minimal example:
```python
import torch
from torchsummary import summary


class TestModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self._layers = torch.nn.ModuleList()
        self._layers.append(torch.nn.Linear(5,5))
        self._layers.append(torch.nn.Linear(5,5))

    def forward(self, x):
        out = x
        for l in self._layers:
            out = l(x)
        return out


if __name__ == "__main__":
    my_module = TestModule()
    summary(my_module, (5,))

```
Gives
```bash
------------------------------------------------------------------------------------------
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
==========================================================================================
Total params: 60
Trainable params: 60
Non-trainable params: 0
Total mult-adds (M): 0.00
------------------------------------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
------------------------------------------------------------------------------------------
```

Whereas the `print(str(model))` gives
```bash
TestModule(
  (_layers): ModuleList(
    (0): Linear(in_features=5, out_features=5, bias=True)
    (1): Linear(in_features=5, out_features=5, bias=True)
  )
)
```

Is this expected behavior? I could probably work on a PR if you think this should be changed and you have no quick fix for it.

**Comment by TylerYep** [comment]
This should be changed! If you would like to start a PR, that would be awesome!

**Comment by roym899** [comment]
Alright. I'll work on a PR.

**Comment by WZTENG** [comment]
I also encountered the same problem and there was no network information.

**Comment by roym899** [comment]
So I started looking into this, and this happens when the parent module is not called. As a quick workaround passing `branching=False` works as a workaround to see the nested layers, but removes the hierarchical output.

@TylerYep I'm not sure what the 'right' way to handle this would be. I made a fix where I store the parent of each module and print its full hierarchy from the point where the current hierarchy is different. The question is how to handle indexing correctly. Currently it assigns one index for each call to a layer, but now some layers are not called. If I instead assign an index on creation, that would print the same index, if a layer is called twice (breaking the tests, not sure if this would be better though?) For now I made it so that these layers will not show an index, and otherwise indexing is unchanged.

**Comment by TylerYep** [comment]
The changes look really great! I left a few minor comments on the PR. Functionality-wise it looks good to merge, but it would be great if you could add tests for all of the models you tried.

To do so, just add models to fixtures/models.py, and add each call to torchsummary_test.py. Output tests are optional, since the ModuleList output is subject to change.

I will think about the indexing strategy a bit more, but seeing as none of the previous test cases have broken, these changes seem good to merge - I'll add a note that Sequential and ModuleList support is in-progress.
